"""source connections, oauth state, sync runs

Revision ID: 7c911d7aa785
Revises: 0001_initial
Create Date: 2026-08-30 15:50:39.550662
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_source_connections"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_secret",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("key_fingerprint", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_secret", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_secret_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "oauth_authorization",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("secret_ref", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secret_ref"],
            ["source_secret.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
    )
    with op.batch_alter_table("oauth_authorization", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_state_hash"), ["state_hash"], unique=False
        )

    op.create_table(
        "source_connection",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_account_id", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("auth_ref", sa.String(length=36), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("sync_cursor", sa.JSON(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consent_granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('disconnected','authorizing','connected','syncing',"
            "'degraded','reauth_required','error')",
            name="ck_source_connection_status",
        ),
        sa.ForeignKeyConstraint(
            ["auth_ref"],
            ["source_secret.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "source", "external_account_id"),
    )
    with op.batch_alter_table("source_connection", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_connection_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_source_connection_source"), ["source"], unique=False)

    op.create_table(
        "sync_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("source_connection_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("counters", sa.JSON(), nullable=False),
        sa.Column("cursor_before", sa.JSON(), nullable=False),
        sa.Column("cursor_after", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running','succeeded','partial','failed')", name="ck_sync_run_status"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"],
            ["source_connection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_run", schema=None) as batch_op:
        batch_op.create_index(
            "idx_sync_run_connection", ["source_connection_id", "started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sync_run_owner_id"), ["owner_id"], unique=False)

    # Named explicitly: an anonymous constraint cannot be dropped again on PostgreSQL.
    with op.batch_alter_table("interaction_event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_connection_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_interaction_event_source_connection",
            "source_connection",
            ["source_connection_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interaction_event", schema=None) as batch_op:
        batch_op.drop_constraint("fk_interaction_event_source_connection", type_="foreignkey")
        batch_op.drop_column("source_connection_id")

    with op.batch_alter_table("sync_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_run_owner_id"))
        batch_op.drop_index("idx_sync_run_connection")

    op.drop_table("sync_run")
    with op.batch_alter_table("source_connection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_connection_source"))
        batch_op.drop_index(batch_op.f("ix_source_connection_owner_id"))

    op.drop_table("source_connection")
    with op.batch_alter_table("oauth_authorization", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_state_hash"))
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_owner_id"))

    op.drop_table("oauth_authorization")
    with op.batch_alter_table("source_secret", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_secret_owner_id"))

    op.drop_table("source_secret")
    # ### end Alembic commands ###
